# Generated by Django 5.1.6 on 2025-02-25 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course title', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_authors', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='related_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type of asignment', models.CharField(choices=[('lecture', 'Lecture'), ('manual', 'Manual'), ('file', 'File'), ('essay', 'Essay'), ('test', 'Test'), ('exam', 'Exam')], max_length=8)),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True)),
                ('Deadline', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignment_authors', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_asignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(default=None, upload_to='courses/student_files')),
                ('Answer text', models.TextField(blank=True, null=True)),
                ('Test answers', models.JSONField(blank=True, null=True)),
                ('Send at', models.DateTimeField(auto_now_add=True)),
                ('Grade', models.IntegerField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='courses.asignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
